apiVersion: v1
kind: Pod
metadata:
  name: gitea-pgprobe
  namespace: gitea
  labels:
    app.kubernetes.io/name: gitea-pgprobe
spec:
  restartPolicy: Never
  terminationGracePeriodSeconds: 0

  containers:
    - name: psql
      image: postgres:18-alpine
      command: ["sleep", "600"]

      resources:
        requests:
          cpu: 10m
          memory: 32Mi
        limits:
          memory: 128Mi

      env:
        - name: PGHOST
          value: pg-rw.cnpg.svc.cluster.local
        - name: PGDATABASE
          value: gitea
        - name: PGSSLMODE
          value: required
        - name: PGUSER
          valueFrom:
            secretKeyRef:
              name: gitea-db-creds
              key: username
        - name: PGPASSWORD
          valueFrom:
            secretKeyRef:
              name: gitea-db-creds
              key: password
