apiVersion: v1
kind: Namespace
metadata:
  name: ingress-test

---

apiVersion: apps/v1
kind: Deployment
metadata:
  name: echo
  namespace: ingress-test
spec:
  replicas: 1
  selector:
    matchLabels:
      app: echo
  template:
    metadata:
      labels:
        app: echo
    spec:
      containers:
        - name: echo
          image: nginx:alpine
          ports:
            - containerPort: 80

---

apiVersion: v1
kind: Service
metadata:
  name: echo
  namespace: ingress-test
spec:
  selector:
    app: echo
  ports:
    - port: 80
      targetPort: 80

---

apiVersion: networking.k8s.io/v1
kind: Ingress
metadata:
  name: echo
  namespace: ingress-test
spec:
  rules:
    - host: echo.umtdg.com
      http:
        paths:
          - path: /
            pathType: Prefix
            backend:
              service:
                name: echo
                port:
                  number: 80
