controller:
  service:
    annotations:
      metallb.io/loadBalancerIPs: 10.10.10.200

  ingressClassResource:
    default: true

  extraArgs:
    default-ssl-certificate: ingress-nginx/wildcard-tls

  resources:
    requests:
      cpu: 100m
      memory: 128Mi

  metrics:
    enabled: false

tcp:
  22: "gitea/gitea-ssh:22"
