apiVersion: apps/v1
kind: Deployment
metadata:
  name: lbprobe
spec:
  replicas: 1

  selector:
    matchLabels:
      app: lbprobe

  template:
    metadata:
      labels:
        app: lbprobe

    spec:
      containers:
        - name: nginx
          image: nginx:1.27-alpine
          ports:
            - containerPort: 80
          resources:
            requests:
              cpu: 10m
              memory: 16Mi
            limits:
              memory: 64Mi

---

apiVersion: v1
kind: Service
metadata:
  name: lbprobe
spec:
  type: LoadBalancer
  selector:
    app: lbprobe
  ports:
    - protocol: TCP
      port: 80
      targetPort: 80
