apiVersion: v1
kind: Namespace
metadata:
  name: cnpg

---

apiVersion: postgresql.cnpg.io/v1
kind: Cluster
metadata:
  name: pg
  namespace: cnpg
spec:
  instances: 1

  storage:
    size: 50Gi
    storageClass: local-path

  resources:
    requests:
      cpu: 250m
      memory: 512Mi
    limits:
      memory: 2Gi

  postgresql:
    parameters:
      max_connections: "100"
      shared_buffers: "256MB"

  bootstrap:
    initdb:
      database: app
      owner: app

  managed:
    roles:
      - name: portfolio
        ensure: present
        login: true
        passwordSecret:
          name: pfo-db-creds
      - name: gitea
        ensure: present
        login: true
        passwordSecret:
          name: gitea-db-creds

---

apiVersion: postgresql.cnpg.io/v1
kind: Database
metadata:
  name: portfolio
  namespace: cnpg
spec:
  cluster:
    name: pg
  name: portfolio
  owner: portfolio
  databaseReclaimPolicy: retain

---

apiVersion: postgresql.cnpg.io/v1
kind: Database
metadata:
  name: gitea
  namespace: cnpg
spec:
  cluster:
    name: pg
  name: gitea
  owner: gitea
  databaseReclaimPolicy: retain
