apiVersion: v1
kind: Pod
metadata:
  name: pgprobe
  namespace: cnpg
spec:
  restartPolicy: Never

  containers:
    - name: pgprobe
      image: postgres:17-alpine
      command: ["sleep", "3600"]

      resources:
        requests:
          cpu: 10m
          memory: 32Mi
        limits:
          memory: 128Mi

      env:
        - name: PGHOST
          value: pg-rw.cnpg.svc.cluster.local
        - name: PGDATABASE
          value: portfolio
        - name: PGUSER
          valueFrom:
            secretKeyRef:
              name: pfo-db-creds
              key: username
        - name: PGPASSWORD
          valueFrom:
            secretKeyRef:
              name: pfo-db-creds
              key: password
